In [8]:
import time
start = time.time()
my_List = [1,2,3,4,5]
my_List = (i*2 for i in range(1000000))
print('Multiplication time for list res: ' , time.time() - start )

start = time.time()
np_arr = np.arange(1000000)*2

print('\n Numpy Opration time :', time.time() - start)

Multiplication time for list res:  7.581710815429688e-05

 Numpy Opration time : 0.003816366195678711


In [9]:
import numpy as np
#creating the array


zeros = np.zeros((2,3))
print('Zeros array is: \n', zeros)

ones = np.ones((2,3))
print('ones array is: \n', ones)

Zeros array is: 
 [[0. 0. 0.]
 [0. 0. 0.]]
ones array is: 
 [[1. 1. 1.]
 [1. 1. 1.]]


In [10]:
import numpy as np

a = np.arange(1, 21)
b = np.linspace(1, 5, 10)
c = np.zeros((3,4))
d = np.ones((2,5))
e = np.random.rand(4,4)

print(a, b, c, d, e, sep="\n\n")


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[0.23880021 0.3189655  0.60594803 0.00813501]
 [0.53411985 0.43632296 0.35854751 0.86003899]
 [0.46615746 0.03419565 0.30867581 0.07761048]
 [0.09308405 0.54714963 0.6405188  0.09904521]]


In [11]:
#Vactor , Matrix, tensor

import numpy as np

vactor = np.array([1,2,3])
print("vactor: ", vactor)

matrix  = np.array([[1,2],[3,4]])
print('matrix: ', matrix)

tensor = np.array([[[1,2],[3,4],
                    [5,6],[7,8]]])
print('tensor: \n', tensor)

vactor:  [1 2 3]
matrix:  [[1 2]
 [3 4]]
tensor: 
 [[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


In [12]:
# Array properties

arr = np.array([[1,2,3],[4,5,6]])

print('size : ', arr.size)
print('diamensions : ', arr.ndim)
print('shape : ', arr.shape)
print('Dtype : ', arr.dtype)

size :  6
diamensions :  2
shape :  (2, 3)
Dtype :  int64


In [13]:
#shorting the Arr data

import numpy as np

data1 = np.array([1,2,3,4,5,6,7,8])
print("shoretd array Data: ", np.sort(data1))

# high to low shorting

data2 = np.array([[1,2], [3,4], [5,6]])
print("Top to Bottom shorted datas: ", np.sort(data2, axis=0))

shoretd array Data:  [1 2 3 4 5 6 7 8]
Top to Bottom shorted datas:  [[1 2]
 [3 4]
 [5 6]]


## filter



In [14]:
#filter the even number in numpy

even_num = np.array([1,2,3,4,5,6,7,8,9,10])
Even_number  = even_num[even_num % 2 ==0]
print("Filterd even numbers are :", Even_number)

Filterd even numbers are : [ 2  4  6  8 10]


In [21]:
# filter with Mask
even_num = np.array([1,2,3,4])
mask = even_num >4
print("mask filtered numbers are : ", even_num[mask])


mask filtered numbers are :  []


In [ ]:
# condition array
even_num = np.array([1,2,3,4,5,6,7,8,9,10])
Data_where = np.where(even_num>4, even_num*3, even_num)
print("the where elements are :", Data_where)

the where elements are : [ 1  2  3  4 15 18 21 24 27 30]


In [30]:
# adding arrays

arr1 = np.array([[1,2,3],[3,2,1]])
arr2 = np.array([[4,5,6],[6,5,4]])
print("Concatinated array is :", np.concatenate((arr1, arr2)))
print('compatiblity check :', arr1.shape == arr2.shape)

Concatinated array is : [[1 2 3]
 [3 2 1]
 [4 5 6]
 [6 5 4]]
compatiblity check : True


In [32]:
# adding then new array in exsiting as row/col wise

arr3 = np.array([[1,2,3],[4,5,6]])
new_row = np.array([5,6,7])
print("combined row :", np.vstack((arr3, new_row)))

combined row : [[1 2 3]
 [4 5 6]
 [5 6 7]]


In [ ]:
# Dleting the array elemet but after that it  will still return the array structre
new_row = np.array([5,6,7,1,2,3,4,9,6])
print("array element deletion: ", np.delete(new_row,[0,-1]))

array element deletion:  [6 7 1 2 3 4 9 6]
